export enum Results {
  CACHE_USED = "CACHE_USED",
  CACHE_NOT_USED = "CACHE_NOT_USED",
  CACHE_UPDATE_ERROR = "CACHE_UPDATE_ERROR",
  CACHE_UPDATED = "CACHE_UPDATED",
  BAD_INPUT = "BAD_INPUT",
  BAD_URL = "BAD_URL",
  VALIDATION_STEP_ERROR = "VALIDATION_STEP_ERROR",
  GOOD_URL_VALIDATION = "GOOD_URL_VALIDATION",
  GOOD_URL_SERVER = "GOOD_URL_SERVER",
  SFTP_FILE = "SFTP_FILE",
  SFTP_FOLDER = "SFTP_FOLDER",
  SERVER_ERROR = "SERVER_ERROR",
}
